version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    links:
      - db
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
